language: node_js
node_js:
  - "8"
install:
  - npm install
env:
  - DDIR=deployment-dir
script:
  - mkdir -p $RESOURCEROOT
  - node ./scripts/generateOrcidFile.js
  - npm run build
before_deploy:
  - mkdir -p $TRAVIS_COMMIT
  - cp -r appspec.yml bin server-scripts $TRAVIS_COMMIT
  - zip -r $TRAVIS_COMMIT $TRAVIS_COMMIT
  - mkdir -p $DDIR
  - cp $TRAVIS_COMMIT.zip $DDIR
deploy:
  - provider: s3
    skip-cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    region: $AWS_REGION
    local-dir: $DDIR
    upload-dir: "front/$TRAVIS_BRANCH/"
    on:
      branch: development

