export const REQUEST_EXPORTS_LIST = "curation/REQUEST_EXPORTS_LIST";
export const FAIL_EXPORTS_LIST = "curation/FAIL_EXPORTS_LIST";
export const SUCCESS_EXPORTS_LIST = "curation/SUCCESS_EXPORTS_LIST";
