"use strict";

export const PUBLICATION_ID_CHANGED = "submission/PUBLICATION_ID_CHANGED";
export const ADD_NEW_GENE = "submission/ADD_NEW_GENE";
export const REMOVE_GENE = "submission/REMOVE_GENE";
export const ATTEMPT_VALIDATE_PUBLICATION = "submission/ATTEMPT_VALIDATE_PUBLICATION";
export const VALIDATE_PUBLICATION_SUCCESS = "submission/VALIDATE_PUBLICATION_SUCCESS";
export const VALIDATE_PUBLICATION_FAIL = "submission/VALIDATE_PUBLICATION_FAIL";
export const ATTEMPT_VALIDATE_GENE = "submission/ATTEMPT_VALIDATE_GENE";
export const VALIDATE_GENE_SUCCESS = "submission/VALIDATE_GENE_SUCCESS";
export const VALIDATE_GENE_FAIL = "submission/VALIDATE_GENE_FAIL";
export const UPDATE_GENE_DATA = "submission/UPDATE_GENE_DATA";
export const EDIT_GENE_DATA = "submission/EDIT_GENE_DATA";
export const ADD_NEW_ANNOTATION = "submission/ADD_NEW_ANNOTATION";
export const REMOVE_ANNOTATION = "submission/REMOVE_ANNOTATION";
export const CHANGE_ANNOTATION_TYPE = "submission/CHANGE_ANNOTATION_TYPE";
export const UPDATE_ANNOTATION_DATA = "submission/UPDATE_ANNOTATION_DATA";
export const ATTEMPT_SUBMIT = "submission/ATTEMPT_SUBMIT";
export const SUBMIT_SUCCESS = "submission/SUBMIT_SUCCESS";
export const SUBMIT_FAIL = "submission/SUBMIT_FAIL";
export const RESET_SUBMISSION = "submission/RESET_SUBMISSION";
export const ATTEMPT_KEYWORD_SEARCH = "submission/ATTEMPT_KEYWORD_SEARCH";
export const KEYWORD_SEARCH_SUCCESS = "submission/KEYWORD_SEARCH_SUCCESS";
export const KEYWORD_SEARCH_FAIL = "submission/KEYWORD_SEARCH_FAIL";
export const CLEAR_KEYWORD_SEARCH = "submission/CLEAR_KEYWORD_SEARCH";
export const ADD_EVIDENCE_WITH = "submission/ADD_EVIDENCE_WITH";
export const VALIDATE_EVIDENCE_WITH_SUCCESS = "submission/VALIDATE_EVIDENCE_WITH_SUCCESS";
export const VALIDATE_EVIDENCE_WITH_FAIL = "submission/VALIDATE_EVIDENCE_WITH_FAIL";
export const PREVIEW = "submission/PREVIEW";
export const EDIT = "submission/EDIT";

